Repository labnex/LabNex, pull requests merged in 2025-07, with the labels that each got.

#95 Update token logic, libs and other imprvoments
  app/build.gradle
  app/src/main/java/com/labnex/app/activities/ProfileActivity.java
  app/src/main/java/com/labnex/app/adapters/UserAccountsAdapter.java
  app/src/main/java/com/labnex/app/helpers/CheckAuthorizationStatus.java
  app/src/main/java/com/labnex/app/helpers/Markdown.java
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/values-night-v31/themes.xml
  gradle/libs.versions.toml
  gradle/wrapper/gradle-wrapper.properties
Labels: 🚀 Improvement

#97 Create milestone
  app/src/main/java/com/labnex/app/adapters/ProjectMilestonesAdapter.java
  app/src/main/java/com/labnex/app/bottomsheets/MilestoneActionsBottomSheet.java
  app/src/main/java/com/labnex/app/bottomsheets/ProjectMilestonesBottomSheet.java
  app/src/main/java/com/labnex/app/interfaces/ApiInterface.java
  app/src/main/java/com/labnex/app/models/milestone/CrudeMilestone.java
  app/src/main/res/layout/bottom_sheet_milestone_actions.xml
  app/src/main/res/layout/bottom_sheet_project_milestones.xml
  app/src/main/res/layout/list_milestones.xml
  app/src/main/res/values-night-v31/themes.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 🎉 Feature

#100 Import/export data
  app/src/main/java/com/labnex/app/activities/AppSettingsActivity.java
  app/src/main/java/com/labnex/app/activities/SignInActivity.java
  app/src/main/java/com/labnex/app/bottomsheets/BackupBottomSheet.java
  app/src/main/java/com/labnex/app/database/api/BaseApi.java
  app/src/main/java/com/labnex/app/fragments/HomeFragment.java
  app/src/main/res/drawable/ic_database.xml
  app/src/main/res/layout/activity_app_settings.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/bottom_sheet_backup.xml
  app/src/main/res/layout/fragment_home.xml
  app/src/main/res/layout/section_app_settings_backup.xml
  app/src/main/res/values/strings.xml
Labels: 🎉 Feature

#101 Search issues and merge requests
  app/build.gradle
  app/src/main/java/com/labnex/app/activities/CreateFileActivity.java
  app/src/main/java/com/labnex/app/activities/FileViewActivity.java
  app/src/main/java/com/labnex/app/activities/IssuesActivity.java
  app/src/main/java/com/labnex/app/activities/MergeRequestsActivity.java
  app/src/main/java/com/labnex/app/activities/SignInActivity.java
  app/src/main/java/com/labnex/app/bottomsheets/CommentOnIssueBottomSheet.java
  app/src/main/java/com/labnex/app/bottomsheets/NotesBottomSheet.java
  app/src/main/java/com/labnex/app/bottomsheets/WikiActionsBottomSheet.java
  app/src/main/java/com/labnex/app/interfaces/ApiInterface.java
  app/src/main/java/com/labnex/app/viewmodels/IssuesViewModel.java
  app/src/main/java/com/labnex/app/viewmodels/MergeRequestsViewModel.java
  app/src/main/res/drawable/shape_badge_background.xml
  app/src/main/res/drawable/shape_input.xml
  app/src/main/res/layout/activity_create_file.xml
  app/src/main/res/layout/activity_create_issue.xml
  app/src/main/res/layout/activity_create_merge_request.xml
  app/src/main/res/layout/activity_create_project.xml
  app/src/main/res/layout/activity_profile.xml
  app/src/main/res/layout/activity_project_detail.xml
  app/src/main/res/layout/activity_sign_in.xml
  app/src/main/res/layout/activity_snippet_create.xml
  app/src/main/res/layout/bottom_sheet_comment_on_issue.xml
  app/src/main/res/layout/bottom_sheet_groups_create.xml
  app/src/main/res/layout/bottom_sheet_issues_menu.xml
  app/src/main/res/layout/bottom_sheet_label_actions.xml
  app/src/main/res/layout/bottom_sheet_merge_requests_menu.xml
  app/src/main/res/layout/bottom_sheet_milestone_actions.xml
  app/src/main/res/layout/bottom_sheet_notes.xml
  app/src/main/res/layout/bottom_sheet_project_menu.xml
  app/src/main/res/layout/bottom_sheet_tag_actions.xml
  app/src/main/res/layout/bottom_sheet_wiki_actions.xml
  app/src/main/res/layout/custom_create_branch_dialog.xml
  app/src/main/res/layout/fragment_snippet_file.xml
  app/src/main/res/layout/section_home_app_settings.xml
  gradle/libs.versions.toml
Labels: 🎉 Feature

#103 Fix profile screen crash when social links missing
  app/src/main/java/com/labnex/app/activities/ProfileActivity.java
Labels: 🐛 Bug
